# Generated by Django 4.0.3 on 2022-04-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='institutional_email',
            field=models.EmailField(default=None, max_length=32, unique=True, verbose_name='institutional email'),
        ),
    ]
