# Generated by Django 4.0.3 on 2022-04-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_institutional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='institutional_email',
            field=models.EmailField(max_length=32, unique=True, verbose_name='institutional email'),
        ),
    ]
