# Generated by Django 4.0.3 on 2022-04-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('student', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_one', models.IntegerField(default=0, verbose_name='first semester')),
                ('semeter_two', models.IntegerField(default=0, verbose_name='second semeseter')),
                ('ca_one', models.IntegerField(default=0, verbose_name='first continuous assesment')),
                ('ca_two', models.IntegerField(default=0, verbose_name='second continuous assesment')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
