# Generated by Django 4.0.3 on 2022-04-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='ca_one',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='ca_two',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='semester_one',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='semeter_two',
        ),
        migrations.AddField(
            model_name='mark',
            name='ca',
            field=models.IntegerField(default=0, verbose_name=' continuous assesment'),
        ),
        migrations.AddField(
            model_name='mark',
            name='exam',
            field=models.IntegerField(default=0, verbose_name='Exams assesment'),
        ),
        migrations.AddField(
            model_name='mark',
            name='resit',
            field=models.IntegerField(default=0, verbose_name='Resit'),
        ),
    ]
