# Generated by Django 4.0.3 on 2022-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_remove_mark_ca_one_remove_mark_ca_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mark',
            name='total',
            field=models.IntegerField(default=0, verbose_name='total'),
        ),
    ]
