# Generated by Django 4.0.3 on 2022-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_mark_grade_mark_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
